config/routes.rb
Rails.application.routes.draw do

  resources :idears
  resources :ideas
  resources :platforms
  resources :roles
  resources :users do
    get :make_admin, on: :member
  end

  controller :sessions do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'signup' => 'users#new'
  end

  get 'myideas' => 'ideas#myideas'

  get 'ideadetails' => 'ideas#ideadetails'
  
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  get 'ascending' => 'ideas#ascending'
  get 'descending' => 'ideas#descending'
  get 'newest' => 'ideas#newest'
  get 'oldest' => 'ideas#oldest'

  get 'visitorascending' => 'visitors#ascending'
  get 'visitordescending' => 'visitors#descending'
  get 'visitornewest' => 'visitors#newest'
  get 'visitoroldest' => 'visitors#oldest'






  root to: 'visitors#index'
end

app/models/idea.rb
class Idea < ActiveRecord::Base
	belongs_to :user
	belongs_to :platform
	has_many :idears
	has_many :roles, through: :idears
	validates :title, :idea_description, :skill_description,  presence: true
	

	scope :ascending, -> {order(title: :asc)}
	scope :descending, -> {order(title: :desc)}
	
	scope :newest, -> {order(created_at: :desc)}
	scope :oldest, -> {order(created_at: :asc)}

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  skip_before_action :authenticate, only: [:index, :show]
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  def ascending
    @ideas = Idea.ascending
  end

  def descending
    @ideas = Idea.descending
  end

  def newest
    @ideas = Idea.newest
  end

  def oldest
    @ideas = Idea.oldest
  end  

  def myideas
    @ideas = Idea.all
  end

  def ideadetails
    @ideas = Idea.all
  end


  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end



  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    @idea.user_id=current_user.id

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:title, :idea_description, :skill_description, :user_id, :platform_id, :role_ids => [])
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= simple_form_for(@idea) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :idea_description %>
    <%= f.input :skill_description %>
    <%= f.association :platform %>
    <%= f.association :roles, :as => :check_boxes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ideas/ascending.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ideas</h1>
sort by: <%= link_to 'Ascending', ascending_path %> - 
<%= link_to 'Descending', descending_path %> - 
<%= link_to 'Newest to Oldest', newest_path %> -
<%= link_to 'Oldest to Newest', oldest_path %>
<table>
  <thead>
    <tr>
      <th> Title </th>
      <th>Idea description</th>
      <th>Skill description</th>
      <th>User</th>
      <th>Platform</th>
      

  
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.idea_description %></td>
        <td><%= idea.skill_description %></td>
        <td><%= idea.user%></td>
        <td><%= idea.platform%></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/descending.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ideas</h1>
sort by: <%= link_to 'Ascending', ascending_path %> - 
<%= link_to 'Descending', descending_path %> - 
<%= link_to 'Newest to Oldest', newest_path %> -
<%= link_to 'Oldest to Newest', oldest_path %>
<table>
  <thead>
    <tr>
      <th> Title </th>
      <th>Idea description</th>
      <th>Skill description</th>
      <th>User</th>
      <th>Platform</th>

  
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.idea_description %></td>
        <td><%= idea.skill_description %></td>
        <td><%= idea.user%></td>
        <td><%= idea.platform%></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/ideadetails.html.erb
<p id="notice"><%= notice %></p>

<center> <h4> <font color="white"> IDEAS DETAILS </font> </h4> </center>
<center>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Idea description</th>
      <th>Skill description</th>
      <th>User</th>
      <th>Platform</th>
      <th>Role Status<th>
  

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.idea_description %></td>
        <td><%= idea.skill_description %></td>
        <td><%= idea.user.name %></td>

        <td><% idea.roles.all.each do|role| %> 
          <ul>
            <li>
              <%= role.name%> - 
              <% if idea.idears.find_by(role_id:role.id).filled? %>
              <%= User.find_by(id:(idea.idears.find_by(role_id:role.id).user_id)).name %>
              <% else %>
              <%= link_to 'Register', idear_path(idea.idears.find_by(role_id: role.id)) %> 
          <% end %>
            </li>
           </ul>
           <% end %>

           </td>
        <td><%= idea.platform.name%></td>
        <td><%= link_to 'Show', idea %></td>

        <% if logged_in? && current_user.admin? %>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Idea', new_idea_path %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Idea description</th>
      <th>Skill description</th>
      <th>User</th>
      <th>Role Status<th>
      <th>Platform</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.idea_description %></td>
        <td><%= idea.skill_description %></td>
        <td><%= idea.user.name %></td>

        <td><% idea.roles.all.each do|role| %> 
          <ul>
            <li>
              <%= role.name%> - 
              <% if idea.idears.find_by(role_id:role.id).filled? %>
              <%= User.find_by(id:(idea.idears.find_by(role_id:role.id).user_id)).name %>
              <% else %>
              <%= link_to 'Register', idear_path(idea.idears.find_by(role_id: role.id)) %> 
          <% end %>
            </li>
           </ul>
           <% end %>

           </td>
        <td><%= idea.platform.name%></td>
        <td><%= link_to 'Show', idea %></td>
        <% if current_user.admin? %>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/myideas.html.erb
<p id="notice"><%= notice %></p>
<% @ideas.each do |idea| %>
<% if idea.user_id == current_user.id %>
<center> <h4> <font color="white"> YOUR IDEAS </font> </h4> </center>
<center>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Idea description</th>
      <th>Skill description</th>
      <th>User</th>
      <th>Role Status<th>
      <th>Platform</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.idea_description %></td>
        <td><%= idea.skill_description %></td>
        <td><%= idea.user.name %></td>

        <td><% idea.roles.all.each do|role| %> 
          <ul>
            <li>
              <%= role.name%> - 
              <% if idea.idears.find_by(role_id:role.id).filled? %>
              <%= User.find_by(id:(idea.idears.find_by(role_id:role.id).user_id)).name %>
              <% else %>
              <%= link_to 'Register', idear_path(idea.idears.find_by(role_id: role.id)) %> 
          <% end %>
            </li>
           </ul>
           <% end %>

           </td>

        <td><%= idea.platform.name%></td>
        <td><%= link_to 'Show', idea %></td>
        <% if current_user.admin? %>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>

  </tbody>
</table>
</center>
    <% end %>
     <% end %>

 <%= link_to 'New idea', new_idea_path %> 
</br>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/newest.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ideas</h1>
sort by: <%= link_to 'Ascending', ascending_path %> - 
<%= link_to 'Descending', descending_path %> - 
<%= link_to 'Newest to Oldest', newest_path %> -
<%= link_to 'Oldest to Newest', oldest_path %>
<table>
  <thead>
    <tr>
      <th> Title </th>
      <th>Idea description</th>
      <th>Skill description</th>
      <th>User</th>
      <th>Platform</th>

  
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.idea_description %></td>
        <td><%= idea.skill_description %></td>
        <td><%= idea.user%></td>
        <td><%= idea.platform%></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/oldest.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ideas</h1>
sort by: <%= link_to 'Ascending', ascending_path %> - 
<%= link_to 'Descending', descending_path %> - 
<%= link_to 'Newest to Oldest', newest_path %> -
<%= link_to 'Oldest to Newest', oldest_path %>
<table>
  <thead>
    <tr>
      <th> Title </th>
      <th>Idea description</th>
      <th>Skill description</th>
      <th>User</th>
      <th>Platform</th>

  
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.idea_description %></td>
        <td><%= idea.skill_description %></td>
        <td><%= idea.user%></td>
        <td><%= idea.platform%></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @idea.title %>
</p>

<p>
  <strong>Idea description:</strong>
  <%= @idea.idea_description %>
</p>

<p>
  <strong>Skill description:</strong>
  <%= @idea.skill_description %>
</p>

<p>
  <strong>User:</strong>
  <%= @idea.user.name%>
</p>

<p>
  <strong>Platform:</strong>
  <%= @idea.platform.name%>
</p>

<p>
  <strong> Role Status: </strong>
 <% @idea.roles.all.each do|role| %> 
          <ul>
            <li>
              <%= role.name%> - 
              <% if @idea.idears.find_by(role_id:role.id).filled? %>
              <%= User.find_by(id:(@idea.idears.find_by(role_id:role.id).user_id)).name %>
              <% else %>
              <%= link_to 'Register', idear_path(@idea.idears.find_by(role_id: role.id)) %> 
          <% end %>
            </li>
           </ul>
           <% end %>
</p>


<% if logged_in? %>

<% if current_user.admin? %>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path%>
<% else %>

<%= link_to 'Back', root_path %>
<% end %>
<% end %>