config/routes.rb
Rails.application.routes.draw do

  resources :idears
  resources :ideas
  resources :platforms
  resources :roles
  resources :users do
    get :make_admin, on: :member
  end

  controller :sessions do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'signup' => 'users#new'
  end

  get 'myideas' => 'ideas#myideas'

  get 'ideadetails' => 'ideas#ideadetails'
  
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  get 'ascending' => 'ideas#ascending'
  get 'descending' => 'ideas#descending'
  get 'newest' => 'ideas#newest'
  get 'oldest' => 'ideas#oldest'

  get 'visitorascending' => 'visitors#ascending'
  get 'visitordescending' => 'visitors#descending'
  get 'visitornewest' => 'visitors#newest'
  get 'visitoroldest' => 'visitors#oldest'






  root to: 'visitors#index'
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
skip_before_action :authenticate

def index
	@ideas=Idea.all
	end
	
  def ascending
    @ideas = Idea.ascending
  end

  def descending
    @ideas = Idea.descending
  end

  def newest
    @ideas = Idea.newest
  end

  def oldest
    @ideas = Idea.oldest
  end

end

app/views/visitors/ascending.html.erb
<p id="notice"><%= notice %></p>

<center> <h4> <font color="white"> IDEAS </font> </h4> </center>
<center>
sort by: <%= link_to 'Ascending', ascending_path %> - 
<%= link_to 'Descending', descending_path %> - 
<%= link_to 'Newest to Oldest', newest_path %> -
<%= link_to 'Oldest to Newest', oldest_path %>
</center>
<center>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Idea description</th>
      <th>Skill description</th>
 

      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.idea_description %></td>
        <td><%= idea.skill_description %></td>
    

        <td><%= link_to 'Show', idea %></td>

        <% if logged_in? && current_user.admin? %>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Idea', new_idea_path %> |
<%= link_to 'More Idea Details', ideadetails_path %>

app/views/visitors/descending.html.erb
<p id="notice"><%= notice %></p>

<center> <h4> <font color="white"> IDEAS </font> </h4> </center>
<center>
sort by: <%= link_to 'Ascending', ascending_path %> - 
<%= link_to 'Descending', descending_path %> - 
<%= link_to 'Newest to Oldest', newest_path %> -
<%= link_to 'Oldest to Newest', oldest_path %>
</center>
<center>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Idea description</th>
      <th>Skill description</th>
 

      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.idea_description %></td>
        <td><%= idea.skill_description %></td>
    

        <td><%= link_to 'Show', idea %></td>

        <% if logged_in? && current_user.admin? %>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Idea', new_idea_path %> |
<%= link_to 'More Idea Details', ideadetails_path %>

app/views/visitors/index.html.erb
<p id="notice"><%= notice %></p>

<center> <h4> <font color="white"> IDEAS </font> </h4> </center>
<center>
sort by: <%= link_to 'Ascending', ascending_path %> - 
<%= link_to 'Descending', descending_path %> - 
<%= link_to 'Newest to Oldest', newest_path %> -
<%= link_to 'Oldest to Newest', oldest_path %>
</center>
<center>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Idea description</th>
      <th>Skill description</th>
 

      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.idea_description %></td>
        <td><%= idea.skill_description %></td>
    

        <td><%= link_to 'Show', idea %></td>

        <% if logged_in? && current_user.admin? %>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Idea', new_idea_path %> |
<%= link_to 'More Idea Details', ideadetails_path %>

app/views/visitors/newest.html.erb
<p id="notice"><%= notice %></p>

<center> <h4> <font color="white"> IDEAS </font> </h4> </center>
<center>
sort by: <%= link_to 'Ascending', ascending_path %> - 
<%= link_to 'Descending', descending_path %> - 
<%= link_to 'Newest to Oldest', newest_path %> -
<%= link_to 'Oldest to Newest', oldest_path %>
</center>
<center>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Idea description</th>
      <th>Skill description</th>
 

      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.idea_description %></td>
        <td><%= idea.skill_description %></td>
    

        <td><%= link_to 'Show', idea %></td>

        <% if logged_in? && current_user.admin? %>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Idea', new_idea_path %> |
<%= link_to 'More Idea Details', ideadetails_path %>

app/views/visitors/oldest.html.erb
<p id="notice"><%= notice %></p>

<center> <h4> <font color="white"> IDEAS </font> </h4> </center>
<center>
sort by: <%= link_to 'Ascending', ascending_path %> - 
<%= link_to 'Descending', descending_path %> - 
<%= link_to 'Newest to Oldest', newest_path %> -
<%= link_to 'Oldest to Newest', oldest_path %>
</center>
<center>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Idea description</th>
      <th>Skill description</th>
 

      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.idea_description %></td>
        <td><%= idea.skill_description %></td>
    

        <td><%= link_to 'Show', idea %></td>

        <% if logged_in? && current_user.admin? %>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Idea', new_idea_path %> |
<%= link_to 'More Idea Details', ideadetails_path %>