config/routes.rb
Rails.application.routes.draw do

  resources :idears
  resources :ideas
  resources :platforms
  resources :roles
  resources :users do
    get :make_admin, on: :member
  end

  controller :sessions do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'signup' => 'users#new'
  end

  get 'myideas' => 'ideas#myideas'

  get 'ideadetails' => 'ideas#ideadetails'
  
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  get 'ascending' => 'ideas#ascending'
  get 'descending' => 'ideas#descending'
  get 'newest' => 'ideas#newest'
  get 'oldest' => 'ideas#oldest'

  get 'visitorascending' => 'visitors#ascending'
  get 'visitordescending' => 'visitors#descending'
  get 'visitornewest' => 'visitors#newest'
  get 'visitoroldest' => 'visitors#oldest'






  root to: 'visitors#index'
end

app/models/idear.rb
class Idear < ActiveRecord::Base
belongs_to :idea 
belongs_to :role
has_one :user
end

app/controllers/idears_controller.rb
class IdearsController < ApplicationController
  before_action :set_idear, only: [:show, :edit, :update, :destroy]

  # GET /idears
  # GET /idears.json
  def index
    @idears = Idear.all
  end

  # GET /idears/1
  # GET /idears/1.json
  def show
  end

  # GET /idears/new
  def new
    @idear = Idear.new
  end

  # GET /idears/1/edit
  def edit
  end

  # POST /idears
  # POST /idears.json
  def create
    @idear = Idear.new(idear_params)

    respond_to do |format|
      if @idear.save
        format.html { redirect_to @idear, notice: 'Idear was successfully created.' }
        format.json { render :show, status: :created, location: @idear }
      else
        format.html { render :new }
        format.json { render json: @idear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /idears/1
  # PATCH/PUT /idears/1.json
  def update
    respond_to do |format|
      if @idear.update(idear_params)
        @idear.user_id=current_user.id
        @idear.save
        format.html { redirect_to root_path, notice: 'Idea Role Successfully Updated' }
        format.json { render :index, status: :ok, location: root_path }
      else
        flash[:error] = 'Request Process Unsuccessful'
        format.html { render :edit }
        format.json { render json: @idear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /idears/1
  # DELETE /idears/1.json
  def destroy
    @idear.destroy
    respond_to do |format|
      format.html { redirect_to idears_url, notice: 'Idear was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idear
      @idear = Idear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idear_params
      params.require(:idear).permit(:filled)
    end
end

app/helpers/idears_helper.rb
module IdearsHelper
end

app/views/idears/_form.html.erb
<%= simple_form_for(@idear) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :role_id %>
    <%= f.input :user_id %>
    <%= f.input :idea_id %>
    <%= f.input :filled %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/idears/_register.html.erb
<%= simple_form_for(@idear) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :filled %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/idears/edit.html.erb
<h1>Editing Idear</h1>

<%= render 'form' %>

<%= link_to 'Show', @idear %> |
<%= link_to 'Back', idears_path %>

app/views/idears/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Idears</h1>

<table>
  <thead>
    <tr>
      <th>Role</th>
      <th>User</th>
      <th>Idea</th>
      <th>Filled</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @idears.each do |idear| %>
      <tr>
        <td><%= idear.role_id %></td>
        <td><%= idear.user_id %></td>
        <td><%= idear.idea_id %></td>
        <td><%= idear.filled %></td>
        
        <td><%= link_to 'Show', idear %></td>
        <td><%= link_to 'Edit', edit_idear_path(idear) %></td>
        <td><%= link_to 'Destroy', idear, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idear', new_idear_path %>

app/views/idears/new.html.erb
<h1>New Idear</h1>

<%= render 'form' %>

<%= link_to 'Back', idears_path %>

app/views/idears/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idea:</strong>
  <%= Idea.find_by(id: (@idear.idea_id)).title %>
</p>

<p>
  <strong>Role:</strong>
  <%= Role.find_by(id:(@idear.role_id)).name %>
</p>

<%= render 'register' %>

<%= link_to 'Back', ideas_path %>