config/routes.rb
Rails.application.routes.draw do

  resources :idears
  resources :ideas
  resources :platforms
  resources :roles
  resources :users do
    get :make_admin, on: :member
  end

  controller :sessions do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'signup' => 'users#new'
  end

  get 'myideas' => 'ideas#myideas'

  get 'ideadetails' => 'ideas#ideadetails'
  
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  get 'ascending' => 'ideas#ascending'
  get 'descending' => 'ideas#descending'
  get 'newest' => 'ideas#newest'
  get 'oldest' => 'ideas#oldest'

  get 'visitorascending' => 'visitors#ascending'
  get 'visitordescending' => 'visitors#descending'
  get 'visitornewest' => 'visitors#newest'
  get 'visitoroldest' => 'visitors#oldest'






  root to: 'visitors#index'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name"><%= link_to 'Home', root_path
    %></li>
        <li class="toggle-topbar menu-icon"><a
    href="#">Menu</a></li>
      </ul>
      <div class="top-bar-section">
        <ul class="left">
          <%= render 'layouts/navigation_links_left' %>
        </ul>
        <ul class="right">
          <%= render 'layouts/navigation_links_right' %>
        </ul>
      </div>
    </nav>

app/views/layouts/_navigation_links_left.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Ideas', ideas_path%></li>
 <% if logged_in? %>
 <li><%= link_to 'Users', users_path %></li>
	<% if current_user.admin? %>

<li><%= link_to 'Platforms', platforms_path %></li>
<li><%= link_to 'Roles', roles_path %></li>

<% end %>
<% end %>
<li><%= link_to 'Help Center', page_path('helpcenter') %></li>

app/views/layouts/_navigation_links_right.html.erb
<% if logged_in? %>
      <li><%= link_to 'Logout', logout_path, method:
    :delete%></li>
      <li><%= link_to 'My Account', current_user%></li>
      <li><%= link_to 'My Ideas', myideas_path%></li>      
    <% else %>
      <li><%= link_to 'Login', login_path %></li>
      <li><%= link_to 'Sign up', signup_path %></li>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fpaim" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Fpaim" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>